#!/bin/bash
##PBS -l nodes=1:ppn=4
#PBS -l nodes=1:cuda
#PBS -l walltime=16:00:00
#PBS -N mv
#PBS -o out_cuda.$PBS_JOBID
#PBS -e err_cuda.$PBS_JOBID
#PBS -r n
#PBS -V
##PBS -m abe
##PBS -M cding@mines.edu
#-----------------------------------------------------
cd $PBS_O_WORKDIR
./mv
